/**
 * Persistence check: query records that were generated by the previous test.
 * Usage: npx ts-node scripts/check-persistence.ts
 */
import prisma from "../src/services/db";

async function main() {
  const dateStr = "2026-02-16";

  console.log("=== DB Persistence Check ===\n");
  console.log(`Checking records for date: ${dateStr}\n`);

  const count = await prisma.timeRecord.count({ where: { date: dateStr } });
  console.log(`Total records in DB: ${count}`);

  if (count === 0) {
    console.log("\n❌ NO records found. They were NOT persisted.");
    await prisma.$disconnect();
    return;
  }

  console.log(`\n✅ ${count} records ARE persisted in the database.\n`);

  // Show 5 samples
  const samples = await prisma.timeRecord.findMany({
    where: { date: dateStr },
    take: 5,
    select: {
      id: true,
      employeeName: true,
      date: true,
      entrada: true,
      salida: true,
      inicioColacion: true,
      finColacion: true,
      status: true,
      shiftPatternName: true,
    },
  });

  console.log("=== 5 Sample Records ===");
  for (const r of samples) {
    console.log(
      `  ${(r.employeeName ?? "?").padEnd(25)} | entrada=${(r.entrada ?? "NULL").padEnd(5)} | salida=${(r.salida ?? "NULL").padEnd(5)} | colacion=${r.inicioColacion ?? "NULL"}-${r.finColacion ?? "NULL"} | status=${r.status} | shift=${r.shiftPatternName ?? "none"}`,
    );
  }

  // Check for nulls
  const nullEntrada = await prisma.timeRecord.count({
    where: { date: dateStr, entrada: null, status: "Cerrado" },
  });
  const nullSalida = await prisma.timeRecord.count({
    where: { date: dateStr, salida: null, status: "Cerrado" },
  });
  console.log(`\n=== Null Check (only 'Cerrado' records) ===`);
  console.log(`  Cerrado records with NULL entrada: ${nullEntrada}`);
  console.log(`  Cerrado records with NULL salida:  ${nullSalida}`);

  if (nullEntrada > 0 || nullSalida > 0) {
    console.log("\n⚠️  Found Cerrado records with null times. Showing examples:");
    const nullExamples = await prisma.timeRecord.findMany({
      where: {
        date: dateStr,
        status: "Cerrado",
        OR: [{ entrada: null }, { salida: null }],
      },
      take: 3,
      select: {
        id: true,
        employeeName: true,
        entrada: true,
        salida: true,
        scheduledStartTime: true,
        scheduledEndTime: true,
      },
    });
    for (const r of nullExamples) {
      console.log(
        `    ${r.employeeName}: entrada=${r.entrada} salida=${r.salida} sched=${r.scheduledStartTime}-${r.scheduledEndTime}`,
      );
    }
  }

  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
