export const liberalitasDefinitions = [
  "Virtud romana — a menudo ignorada por la gestión moderna.",
  "Rara vez incluida en las evaluaciones de desempeño.",
  "Incompatible con los objetivos trimestrales.",
  "Antigua virtud, hoy archivada bajo 'no rentable'.",
  "Dar sin esperar nada… como cuando haces horas extra 'voluntarias'.",
  "Ideal romano que jamás sobreviviría a una junta de accionistas.",
  "Virtud descontinuada en ambientes laborales modernos.",
  "Generosidad genuina — no confundida con 'team building'.",
  "Acto noble sin métricas… ni reconocimiento, claro está.",
  "El noble arte de dar, sin esperar ni una caja Navideña.",
  "Cuando aportas más de lo que figura en tu contrato.",
  "Donar talento en un entorno que sólo mide presencia.",
  "La antigua costumbre de entregar el alma por cero feedback.",
  "Una práctica milenaria, hoy confundida con 'actitud proactiva'.",
  "Virtud clásica: dar sin Excel de respaldo.",
  "Equivalente moral de hacer deploy un viernes... por el bien común.",
  "La buena voluntad antes de que existiera el 'job burnout'.",
  "Generosidad silenciada por reuniones sin propósito.",
  "¿Reconocimiento? No, gracias. Soy del siglo I a.C.",
  "Actuar con ética, incluso cuando el jefe no está mirando.",
  "Romana, ética, gloriosa… todo lo que no fue tu última evaluación.",
  "Acción noble sin comité, sin presupuesto, sin aplausos.",
  "El acto de dar... y luego ver cómo el crédito va a otro.",
  "Cuando compartes tu idea… y luego la ves patentada por alguien más.",
  "Dar sin esperar ni siquiera un emoji de agradecimiento.",
  "Una acción sin ROI, pero con legado.",
  "La virtud que los algoritmos de RRHH aún no pueden medir.",
  "Como el código limpio: nadie lo ve, pero todos se benefician.",
  "Concepto obsoleto según los indicadores de productividad modernos.",
  "Más rara que un aumento sin tener que pedirlo.",
  "Probablemente lo que haría un buen líder… si existiera.",
];

// Frases exclusivas para modo desarrollador (más hardcore)
export const devOnlyDefinitions = [
  "Modo Desarrollador: cuando liberalitas es literalmente tu stack.",
  "Contribución invisible, pero sin la cual todo explota.",
  "Tu esfuerzo no está en los logs, pero está en el alma del sistema.",
];
